### PR TITLE
Proof-read 2017-06-04-eventsourcing-in-haskell.markdown

### PR DESCRIPTION
**Pull request by NamelessCoder**
* Ran through whitespace to homogenise
* Fixed a few sentence structure problems
* Adjusted a few wordings to read better internally

Suggestion: adjust example about domain entity to avoid the whole mentioning of "don't do this, use newtype instead". It might be confusing and for sure detracts attention ;)

### CODE REVIEW

**Comment by NamelessCoder** [comment]
Oh almost forgot, overall remark: easy to follow if you already know about event sourcing; and I expect easy enough to get into if you don't (with the hurdle of stolen attention in the "don't do this" notice). Pretty good writeup I'd say although I didn't run your examples!

**Comment by Akii** [comment]
First of all thank you very much for proofreading!

Regarding newtype: Yeah the newtype thing bugged me as well. Why not just use newtype instead of explaining not to use it. Will change.

One question: is it always "aggregate's" instead of "aggregates"? If so, I should change all occurrences  of that in the post.

**Comment by Akii** [comment]
Also the changes make it much easier to read, some sentences were just awkward xD

**Comment by NamelessCoder** [comment]
> One question: is it always "aggregate's" instead of "aggregates"? If so, I should change all occurrences of that in the post.

The only occurrence I found is one instance where it looked like the meaning was `aggregate's` as in "the XYZ of the aggregate" rather than the plural of aggregate. Never use apostrophe before the `s` for plural form with the only exception being plural forms of (some) acronyms.

**Comment by Akii** [comment]
Gotcha! :3 Fixed the newtype thing as well; but first let me merge this.

Thanks again!

**Comment by Akii** [comment]
That was rather easy: https://github.com/Akii/blog/commit/ee6d53797e61a21b331fd6d593da635353299ced

xD Haskell is so good..

**Pull request merged**
